# Generated by Django 4.0.3 on 2023-06-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestiary',
            name='Immunity_State',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='Salvage',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='Senses',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='Subspecies',
        ),
        migrations.RemoveField(
            model_name='bestiary',
            name='Vulnerability_Damage',
        ),
    ]
