# Generated by Django 4.0.3 on 2023-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='summury',
            new_name='Summary',
        ),
    ]
